version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.15.0
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp build s3://reactjs-study-aws-dev --recursive --acl public-read
